

#!/bin/bash

echo "Jenkins Pipeline Script"

echo "Starting the Pipeline Script"

# Start the Pipeline
pipeline {
    agent any
 
    stages {
        stage('Clone') {
            steps {
                git 'https://github.com/my_repo/my_project.git'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Deploy') {
            steps {
                sh 'mvn deploy'
            }
        }
    }
    post {
        success {
            echo 'Build success!'
        }
        failure {
            echo 'Build failed.'
        }
